/**
 * @file    i2c.h
 * @brief   Universal I2C (Inter-Integrated Circuit) Driver Library
 * @version 2.0.0
 * @date    2024
 *
 * ============================================================================
 *                        I2C PROTOCOL OVERVIEW
 * ============================================================================
 *
 * I2C (Inter-Integrated Circuit), also written I²C or IIC, is a synchronous,
 * multi-master, multi-slave, serial communication bus developed by Philips
 * Semiconductor (now NXP) in 1982 for connecting low-speed peripherals.
 *
 * PHYSICAL BUS:
 *   - SDA  : Serial Data Line  — bidirectional data
 *   - SCL  : Serial Clock Line — generated by master
 *   - Both lines are OPEN-DRAIN and require pull-up resistors to VCC
 *   - Typical pull-up values: 4.7kΩ (standard), 2.2kΩ (fast), 1kΩ (fast+)
 *
 *                VCC       VCC
 *                 |         |
 *               4.7k      4.7k   <-- Pull-up resistors (required!)
 *                 |         |
 *    MASTER ------+---SDA---+------ SLAVE1 --- SLAVE2 --- ...
 *    MASTER ------+---SCL---+------ SLAVE1 --- SLAVE2 --- ...
 *
 * SPEED MODES:
 *   - Standard Mode (Sm)    :   100 kbps
 *   - Fast Mode (Fm)        :   400 kbps
 *   - Fast Mode Plus (Fm+)  :     1 Mbps
 *   - High Speed (Hs)       :   3.4 Mbps
 *   - Ultra Fast (UFm)      :     5 Mbps (unidirectional only)
 *
 * ADDRESSING:
 *   - 7-bit  addressing: up to 112 usable addresses (0x08 – 0x77)
 *   - 10-bit addressing: up to 1008 usable addresses
 *   - Reserved addresses: 0x00 (general call), 0x01–0x07, 0x78–0x7F
 *
 * ============================================================================
 *                        TRANSACTION FORMAT
 * ============================================================================
 *
 * WRITE transaction:
 *   START | ADDR[7:1] W(0) | ACK | DATA[0] | ACK | DATA[1] | ACK | ... | STOP
 *
 * READ transaction:
 *   START | ADDR[7:1] R(1) | ACK | DATA[0] | ACK | DATA[1] | NACK | STOP
 *
 * REPEATED START (combined read/write without releasing the bus):
 *   START | ADDR W | ACK | REG | ACK | RSTART | ADDR R | ACK | DATA | NACK | STOP
 *
 * BIT TIMING:
 *   - Data valid during HIGH SCL
 *   - SDA may change only when SCL is LOW
 *   - START : SDA HIGH→LOW while SCL HIGH
 *   - STOP  : SDA LOW→HIGH while SCL HIGH
 *
 * ============================================================================
 *                        REAL-WORLD USAGE (2024)
 * ============================================================================
 *
 * I2C is used everywhere low-bandwidth peripheral communication is needed:
 *
 *  [SENSORS & ENVIRONMENT]
 *   - BME280 / BME680   : Temperature, Humidity, Pressure (IoT, Weather stations)
 *   - MPU-6050 / ICM-42688 : 6-axis IMU (Drones, Wearables, VR headsets)
 *   - BMP390            : Barometric pressure (Altimeters, Smartphones)
 *   - SHT31 / HDC1080   : Humidity/Temperature (Industrial HVAC)
 *   - VEML7700 / BH1750 : Ambient light (Auto display brightness)
 *   - VL53L1X           : Time-of-Flight distance (Robots, Phones)
 *   - ADS1115           : 16-bit ADC (Precision data acquisition)
 *   - INA226 / INA3221  : Current/Power monitor (Battery management)
 *   - MAX30105           : Pulse oximeter (Medical wearables)
 *   - MLX90614           : IR thermometer (Contactless medical, automotive)
 *
 *  [DISPLAYS & OUTPUT]
 *   - SSD1306 / SSD1315 : OLED display (Smart watches, IoT displays)
 *   - SH1106            : OLED 128×64 (DIY projects, hobbyist boards)
 *   - PCA9685           : 16-ch PWM driver (Servo robots, LED matrices)
 *   - IS31FL3741        : LED matrix driver (Keyboards, wearables)
 *   - HT16K33           : LED matrix driver (7-segment displays)
 *
 *  [MEMORY & STORAGE]
 *   - AT24CXX / M24CXX  : EEPROM (Configuration storage, calibration data)
 *   - M95XXX            : FRAM (Industrial logging)
 *
 *  [POWER MANAGEMENT]
 *   - BQ25895 / BQ24074 : Battery charger IC (Smartphones, laptops)
 *   - MAX17048           : Fuel gauge (Battery % estimation)
 *   - TPS65090           : Power management (Chromebooks, embedded Linux)
 *   - LP8755            : Multi-phase buck converter (Qualcomm SoCs)
 *
 *  [CONNECTIVITY & GPIO EXPANSION]
 *   - PCF8574 / MCP23017 : GPIO expander (When MCU pins are limited)
 *   - PCA9555            : 16-bit I/O expander (Industrial PLCs)
 *   - TCA9548A           : 1-to-8 I2C multiplexer (Multiple same-address sensors)
 *
 *  [CLOCK & TIMING]
 *   - DS3231 / PCF8563  : Real-time clock (Data loggers, embedded Linux boards)
 *   - DS1307            : RTC (Arduino projects, industrial timers)
 *
 *  [AUDIO]
 *   - CS43L22           : DAC/amplifier (STM32 Discovery boards, audio players)
 *   - MAX9867           : Audio codec (Portable audio devices)
 *   - TAS5825M          : Class-D amplifier (Smart speakers)
 *
 *  [AUTOMOTIVE (AEC-Q100 grade devices)]
 *   - TJA1101           : Ethernet PHY (Automotive ADAS)
 *   - PCA9615           : Differential I2C bus buffer (Long-distance automotive bus)
 *   - MCP4716           : DAC (Engine control units)
 *
 *  [INDUSTRIAL & MEDICAL]
 *   - ADT7420           : High-precision temp (Medical equipment)
 *   - LIS2DH12          : Accelerometer (Industrial vibration monitoring)
 *   - SFM3000           : Mass flow meter (Medical ventilators)
 *
 *  [CONSUMER ELECTRONICS]
 *   - Smartphones use 20–50+ I2C devices per device
 *   - Laptops use I2C for batteries (SMBus = I2C subset), keyboard, touchpad
 *   - Smart TVs use I2C for tuners, HDCP, EDID (monitor capabilities)
 *   - DDC/CI monitor control protocol is I2C over HDMI/DisplayPort
 *
 * ============================================================================
 *                        SMBus vs I2C
 * ============================================================================
 *
 * SMBus (System Management Bus) is a subset of I2C, used in:
 *   - Laptop battery management (BQ40Z50, etc.)
 *   - Server BMC (Board Management Controllers)
 *   - PC power supplies (PMBus)
 *   - DDR memory SPD (Serial Presence Detect)
 * Differences: stricter timing, 100kHz max, mandatory ACK timeout, PEC checksum
 *
 * ============================================================================
 *                        THIS LIBRARY FEATURES
 * ============================================================================
 *
 *  [CORE API]
 *   - Software (bit-bang) I2C: works on any GPIO-capable MCU
 *   - Hardware I2C: HAL abstraction layer for STM32, AVR, ESP32, RP2040
 *   - Master write, read, combined write-then-read (register access)
 *   - 7-bit and 10-bit addressing support
 *   - Repeated START support
 *
 *  [ADVANCED FEATURES]
 *   - Multi-master arbitration detection
 *   - Clock stretching support
 *   - Bus recovery (9-clock pulse sequence per I2C spec §3.1.16)
 *   - DMA transfer support (hardware I2C)
 *   - Transaction queue / async API
 *   - Timeout protection on every operation
 *
 *  [DIAGNOSTICS]
 *   - Bus scan: detect all devices on the bus
 *   - Error codes with descriptive messages
 *   - Bus state machine: IDLE, BUSY, ERROR states
 *   - Statistics: transaction count, error count, bus load
 *
 *  [PLATFORM SUPPORT]
 *   - STM32 (HAL-based, all series)
 *   - AVR / Arduino (Wire.h compatible)
 *   - ESP32 / ESP-IDF
 *   - Raspberry Pi / Linux (via /dev/i2c-N)
 *   - Bare-metal / RTOS (FreeRTOS mutex included)
 *   - Portable software I2C fallback (any platform with GPIO)
 *
 * @author  I2C Library Contributors
 * @license MIT License
 */

#ifndef I2C_H
#define I2C_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ============================================================================
 * VERSION
 * ========================================================================== */

#define I2C_LIB_VERSION_MAJOR   2
#define I2C_LIB_VERSION_MINOR   0
#define I2C_LIB_VERSION_PATCH   0
#define I2C_LIB_VERSION_STRING  "2.0.0"

/* ============================================================================
 * CONFIGURATION (override in i2c_config.h before including this file)
 * ========================================================================== */

#ifndef I2C_MAX_INSTANCES
  #define I2C_MAX_INSTANCES       4       /**< Max simultaneous I2C bus instances */
#endif

#ifndef I2C_TIMEOUT_DEFAULT_MS
  #define I2C_TIMEOUT_DEFAULT_MS  100     /**< Default per-operation timeout (ms) */
#endif

#ifndef I2C_RETRY_COUNT
  #define I2C_RETRY_COUNT         3       /**< Retries on NACK before error */
#endif

#ifndef I2C_BUS_RECOVERY_CLOCKS
  #define I2C_BUS_RECOVERY_CLOCKS 9       /**< Clock pulses for bus recovery */
#endif

#ifndef I2C_TX_BUFFER_SIZE
  #define I2C_TX_BUFFER_SIZE      256     /**< Async TX buffer size (bytes) */
#endif

#ifndef I2C_RX_BUFFER_SIZE
  #define I2C_RX_BUFFER_SIZE      256     /**< Async RX buffer size (bytes) */
#endif

#ifndef I2C_ENABLE_10BIT_ADDR
  #define I2C_ENABLE_10BIT_ADDR   1       /**< Enable 10-bit addressing support */
#endif

#ifndef I2C_ENABLE_DMA
  #define I2C_ENABLE_DMA          0       /**< Enable DMA support (hardware only) */
#endif

#ifndef I2C_ENABLE_RTOS
  #define I2C_ENABLE_RTOS         0       /**< Enable FreeRTOS mutex protection */
#endif

/* ============================================================================
 * RESERVED I2C ADDRESSES
 * These addresses are reserved by the I2C specification and must not be used
 * ========================================================================== */

#define I2C_ADDR_GENERAL_CALL       0x00  /**< General Call address (broadcast) */
#define I2C_ADDR_START_BYTE         0x01  /**< Start Byte (legacy fast-mode compat) */
#define I2C_ADDR_CBUS               0x02  /**< CBUS compatibility */
#define I2C_ADDR_FUTURE_BUS         0x03  /**< Reserved for future bus formats */
#define I2C_ADDR_RESERVED_4         0x04  /**< Reserved */
#define I2C_ADDR_RESERVED_5         0x05  /**< Reserved */
#define I2C_ADDR_RESERVED_6         0x06  /**< Reserved */
#define I2C_ADDR_RESERVED_7         0x07  /**< Reserved */
#define I2C_ADDR_10BIT_PREFIX       0x78  /**< 10-bit addressing prefix (0x78–0x7B) */
#define I2C_ADDR_DEVICE_ID          0x7C  /**< Device ID address (for identification) */
#define I2C_ADDR_RESERVED_7D        0x7D  /**< Reserved */
#define I2C_ADDR_RESERVED_7E        0x7E  /**< Reserved */
#define I2C_ADDR_RESERVED_7F        0x7F  /**< Reserved */

/** Valid 7-bit address range */
#define I2C_ADDR_MIN                0x08
#define I2C_ADDR_MAX                0x77

/* ============================================================================
 * ERROR CODES
 * ========================================================================== */

/**
 * @brief I2C operation error codes
 *
 * All API functions return i2c_err_t. Always check the return value.
 * Use i2c_err_to_string() to convert a code to a human-readable message.
 */
typedef enum {
    I2C_OK              =  0,   /**< Success — no error */
    I2C_ERR_NACK_ADDR   = -1,   /**< No ACK on address byte — device not found */
    I2C_ERR_NACK_DATA   = -2,   /**< No ACK during data phase */
    I2C_ERR_ARB_LOST    = -3,   /**< Arbitration lost — another master took the bus */
    I2C_ERR_BUS_BUSY    = -4,   /**< Bus busy — SDA/SCL stuck low */
    I2C_ERR_TIMEOUT     = -5,   /**< Operation timed out */
    I2C_ERR_INVALID_ARG = -6,   /**< NULL pointer or out-of-range argument */
    I2C_ERR_NOT_INIT    = -7,   /**< i2c_init() not called yet */
    I2C_ERR_OVERFLOW    = -8,   /**< Data too large for buffer */
    I2C_ERR_BUS_ERROR   = -9,   /**< Unexpected START or STOP condition */
    I2C_ERR_PLATFORM    = -10,  /**< Platform-specific hardware error */
    I2C_ERR_NO_DEVICE   = -11,  /**< No device responded during scan */
    I2C_ERR_ADDR_RANGE  = -12,  /**< Address outside valid range */
    I2C_ERR_CLK_STRETCH = -13,  /**< Slave holding SCL too long (timeout) */
    I2C_ERR_DMA         = -14,  /**< DMA configuration or transfer error */
} i2c_err_t;

/* ============================================================================
 * ENUMERATIONS
 * ========================================================================== */

/**
 * @brief I2C bus speed mode
 *
 * Choose the speed mode supported by ALL devices on the bus.
 * The actual speed is negotiated to the slowest device.
 */
typedef enum {
    I2C_SPEED_STANDARD  = 100000,   /**< 100 kbps — most compatible, longest wires */
    I2C_SPEED_FAST      = 400000,   /**< 400 kbps — most common embedded usage */
    I2C_SPEED_FAST_PLUS = 1000000,  /**< 1 Mbps   — modern high-speed sensors */
    I2C_SPEED_HIGH      = 3400000,  /**< 3.4 Mbps — near-chip communication only */
} i2c_speed_t;

/**
 * @brief I2C driver type — hardware peripheral or software bit-bang
 *
 * Use I2C_MODE_HARDWARE when the MCU has a dedicated I2C peripheral.
 * Use I2C_MODE_SOFTWARE as fallback on any GPIO-capable platform.
 */
typedef enum {
    I2C_MODE_HARDWARE   = 0,    /**< Use hardware I2C peripheral (faster, DMA capable) */
    I2C_MODE_SOFTWARE   = 1,    /**< Software bit-bang on GPIO pins (portable) */
} i2c_mode_t;

/**
 * @brief I2C bus state
 */
typedef enum {
    I2C_STATE_IDLE      = 0,    /**< Bus is free */
    I2C_STATE_BUSY      = 1,    /**< Transaction in progress */
    I2C_STATE_ERROR     = 2,    /**< Bus in error/stuck state — call i2c_recover() */
    I2C_STATE_SUSPENDED = 3,    /**< Low-power suspend mode */
} i2c_state_t;

/**
 * @brief I2C address size
 */
typedef enum {
    I2C_ADDR_7BIT       = 0,    /**< Standard 7-bit address (0x08–0x77) */
    I2C_ADDR_10BIT      = 1,    /**< Extended 10-bit address */
} i2c_addr_size_t;

/* ============================================================================
 * STRUCTURES
 * ========================================================================== */

/**
 * @brief Platform-specific HAL callbacks
 *
 * Fill this structure to port the library to a new platform.
 * All function pointers MUST be set before calling i2c_init().
 */
typedef struct {
    /**
     * @brief Set SDA pin direction
     * @param output  true = output (drive), false = input (read)
     * @param user_ctx  User-defined context pointer
     */
    void (*sda_dir)(bool output, void *user_ctx);

    /**
     * @brief Set SDA pin output level (only when configured as output)
     * @param level  true = HIGH, false = LOW
     * @param user_ctx  User-defined context pointer
     */
    void (*sda_write)(bool level, void *user_ctx);

    /**
     * @brief Read SDA pin level
     * @return true = HIGH, false = LOW
     * @param user_ctx  User-defined context pointer
     */
    bool (*sda_read)(void *user_ctx);

    /**
     * @brief Set SCL pin level
     * @param level  true = HIGH, false = LOW
     * @param user_ctx  User-defined context pointer
     */
    void (*scl_write)(bool level, void *user_ctx);

    /**
     * @brief Read SCL pin level (for clock stretch detection)
     * @return true = HIGH, false = LOW
     * @param user_ctx  User-defined context pointer
     */
    bool (*scl_read)(void *user_ctx);

    /**
     * @brief Delay in microseconds
     * @param us  Microseconds to delay
     */
    void (*delay_us)(uint32_t us);

    /**
     * @brief Return elapsed time in milliseconds (for timeouts)
     * @return Monotonic millisecond timestamp
     */
    uint32_t (*millis)(void);

    /** User-defined context pointer passed to all callbacks above */
    void *user_ctx;
} i2c_hal_t;

/**
 * @brief I2C bus configuration
 *
 * Example:
 * @code
 * i2c_config_t cfg = {
 *     .mode        = I2C_MODE_SOFTWARE,
 *     .speed       = I2C_SPEED_FAST,
 *     .addr_size   = I2C_ADDR_7BIT,
 *     .timeout_ms  = 50,
 *     .hal         = &my_hal,
 * };
 * @endcode
 */
typedef struct {
    i2c_mode_t      mode;           /**< Hardware or software bit-bang */
    i2c_speed_t     speed;          /**< Bus speed (Hz) */
    i2c_addr_size_t addr_size;      /**< 7-bit or 10-bit addressing */
    uint32_t        timeout_ms;     /**< Per-operation timeout, 0 = use default */
    bool            enable_pullups; /**< Enable internal pull-ups if available */
    bool            enable_dma;     /**< Use DMA for hardware mode transfers */
    i2c_hal_t      *hal;            /**< HAL callbacks (required for software mode) */

    /* Platform-specific hardware config */
    uint8_t         hw_instance;    /**< Hardware I2C instance index (0=I2C1, etc.) */
} i2c_config_t;

/**
 * @brief I2C bus statistics (diagnostic / profiling)
 */
typedef struct {
    uint32_t tx_count;          /**< Total bytes transmitted */
    uint32_t rx_count;          /**< Total bytes received */
    uint32_t transaction_count; /**< Completed transactions */
    uint32_t error_count;       /**< Total errors encountered */
    uint32_t nack_count;        /**< Address NACKs (device not present) */
    uint32_t timeout_count;     /**< Timeout events */
    uint32_t arb_lost_count;    /**< Arbitration loss events */
    uint32_t recovery_count;    /**< Bus recovery attempts */
    uint32_t bus_busy_ms;       /**< Approximate time bus was busy (ms) */
} i2c_stats_t;

/**
 * @brief I2C bus handle
 *
 * Opaque type — do not access fields directly.
 * Obtain from i2c_init(), pass to all API functions.
 */
typedef struct i2c_bus_s *i2c_bus_t;

/* ============================================================================
 * CORE API — INITIALIZATION
 * ========================================================================== */

/**
 * @brief Initialize an I2C bus instance
 *
 * Must be called before any other function. Configures hardware or software
 * driver, sets speed, enables pull-ups if requested.
 *
 * @param[out] bus    Pointer to receive the bus handle
 * @param[in]  cfg    Bus configuration struct
 * @return I2C_OK on success, error code on failure
 *
 * @example
 * @code
 * i2c_bus_t bus;
 * i2c_config_t cfg = {
 *     .mode      = I2C_MODE_HARDWARE,
 *     .speed     = I2C_SPEED_FAST,
 *     .timeout_ms = 50,
 * };
 * if (i2c_init(&bus, &cfg) != I2C_OK) {
 *     // handle error
 * }
 * @endcode
 */
i2c_err_t i2c_init(i2c_bus_t *bus, const i2c_config_t *cfg);

/**
 * @brief De-initialize an I2C bus and release all resources
 *
 * Sends STOP condition if bus is busy, disables hardware peripheral,
 * frees memory. After this call, the handle is invalid.
 *
 * @param bus  Bus handle to deinitialize
 * @return I2C_OK on success
 */
i2c_err_t i2c_deinit(i2c_bus_t bus);

/**
 * @brief Change the I2C bus clock speed at runtime
 *
 * Can be called while bus is idle to adjust speed without full reinit.
 *
 * @param bus    Bus handle
 * @param speed  New speed in Hz (use i2c_speed_t constants)
 * @return I2C_OK on success, I2C_ERR_BUS_BUSY if transaction in progress
 */
i2c_err_t i2c_set_speed(i2c_bus_t bus, i2c_speed_t speed);

/* ============================================================================
 * CORE API — SINGLE-BYTE OPERATIONS
 * These are the atomic building blocks of all I2C communication.
 * For most use cases, prefer the higher-level read/write functions below.
 * ========================================================================== */

/**
 * @brief Send START condition and device address
 *
 * Generates START, then transmits the 7-bit address with R/W bit.
 * Must be followed by i2c_write_bytes() or i2c_read_bytes(), then i2c_stop().
 *
 * @param bus      Bus handle
 * @param addr     7-bit device address (0x08–0x77)
 * @param read     true = read (R/W=1), false = write (R/W=0)
 * @return I2C_OK, I2C_ERR_NACK_ADDR, I2C_ERR_ARB_LOST, I2C_ERR_TIMEOUT
 */
i2c_err_t i2c_start(i2c_bus_t bus, uint8_t addr, bool read);

/**
 * @brief Send REPEATED START condition
 *
 * Used in combined transactions (e.g., write register address, then read data)
 * without releasing the bus. Must follow a previous i2c_start().
 *
 * @param bus   Bus handle
 * @param addr  7-bit device address
 * @param read  Direction for the new phase
 * @return I2C_OK, I2C_ERR_NACK_ADDR, I2C_ERR_ARB_LOST
 */
i2c_err_t i2c_restart(i2c_bus_t bus, uint8_t addr, bool read);

/**
 * @brief Send STOP condition and release the bus
 *
 * @param bus  Bus handle
 * @return I2C_OK always (STOP cannot fail once started)
 */
i2c_err_t i2c_stop(i2c_bus_t bus);

/**
 * @brief Transmit one byte and check ACK
 *
 * @param bus   Bus handle
 * @param byte  Data byte to send
 * @return I2C_OK, I2C_ERR_NACK_DATA, I2C_ERR_ARB_LOST
 */
i2c_err_t i2c_write_byte(i2c_bus_t bus, uint8_t byte);

/**
 * @brief Receive one byte and send ACK or NACK
 *
 * @param bus       Bus handle
 * @param[out] byte Received byte
 * @param ack       true = send ACK (more bytes coming), false = send NACK (last byte)
 * @return I2C_OK, I2C_ERR_TIMEOUT
 */
i2c_err_t i2c_read_byte(i2c_bus_t bus, uint8_t *byte, bool ack);

/* ============================================================================
 * CORE API — MULTI-BYTE OPERATIONS
 * ========================================================================== */

/**
 * @brief Transmit multiple bytes in a single I2C write transaction
 *
 * Generates: START | ADDR W | ACK | data[0] | ACK | ... | data[len-1] | ACK | STOP
 *
 * @param bus   Bus handle
 * @param addr  7-bit device address
 * @param data  Pointer to data buffer to transmit
 * @param len   Number of bytes to send
 * @return I2C_OK, I2C_ERR_NACK_ADDR, I2C_ERR_NACK_DATA, I2C_ERR_TIMEOUT
 *
 * @example
 * @code
 * // Write 0x01 to device 0x3C (e.g., OLED command byte)
 * uint8_t cmd = 0x01;
 * i2c_write(bus, 0x3C, &cmd, 1);
 * @endcode
 */
i2c_err_t i2c_write(i2c_bus_t bus, uint8_t addr, const uint8_t *data, size_t len);

/**
 * @brief Receive multiple bytes in a single I2C read transaction
 *
 * Generates: START | ADDR R | ACK | data[0] | ACK | ... | data[len-1] | NACK | STOP
 *
 * @param bus    Bus handle
 * @param addr   7-bit device address
 * @param[out] data  Buffer to store received bytes
 * @param len    Number of bytes to read
 * @return I2C_OK, I2C_ERR_NACK_ADDR, I2C_ERR_TIMEOUT
 *
 * @example
 * @code
 * // Read 6 bytes from MPU-6050 (accel + gyro raw data)
 * uint8_t raw[6];
 * i2c_read(bus, 0x68, raw, 6);
 * @endcode
 */
i2c_err_t i2c_read(i2c_bus_t bus, uint8_t addr, uint8_t *data, size_t len);

/**
 * @brief Write to a register, then read data (combined transaction)
 *
 * Most sensor ICs use this pattern:
 *   START | ADDR W | ACK | reg | ACK | RSTART | ADDR R | ACK | data... | NACK | STOP
 *
 * This is the most common I2C operation for sensor drivers.
 *
 * @param bus       Bus handle
 * @param addr      7-bit device address
 * @param reg       Register address (1 byte) to write first
 * @param[out] data Buffer to store received data
 * @param len       Number of bytes to read
 * @return I2C_OK, I2C_ERR_NACK_ADDR, I2C_ERR_TIMEOUT
 *
 * @example
 * @code
 * // Read temperature from BMP280 (register 0xFA, 3 bytes)
 * uint8_t raw_temp[3];
 * i2c_write_reg_read(bus, 0x76, 0xFA, raw_temp, 3);
 * @endcode
 */
i2c_err_t i2c_write_reg_read(i2c_bus_t bus, uint8_t addr, uint8_t reg,
                               uint8_t *data, size_t len);

/**
 * @brief Write register address followed by data bytes
 *
 * Used to configure sensor registers:
 *   START | ADDR W | ACK | reg | ACK | data[0] | ACK | ... | STOP
 *
 * @param bus   Bus handle
 * @param addr  7-bit device address
 * @param reg   Register address to write to
 * @param data  Data bytes to write after the register address
 * @param len   Number of data bytes (NOT counting the register byte)
 * @return I2C_OK, I2C_ERR_NACK_ADDR, I2C_ERR_NACK_DATA
 *
 * @example
 * @code
 * // Wake up MPU-6050: write 0x00 to PWR_MGMT_1 register (0x6B)
 * uint8_t val = 0x00;
 * i2c_write_reg(bus, 0x68, 0x6B, &val, 1);
 * @endcode
 */
i2c_err_t i2c_write_reg(i2c_bus_t bus, uint8_t addr, uint8_t reg,
                         const uint8_t *data, size_t len);

/* ============================================================================
 * REGISTER SHORTHAND — Convenient single-register read/write
 * ========================================================================== */

/**
 * @brief Write a single byte to a device register
 *
 * @param bus   Bus handle
 * @param addr  Device address
 * @param reg   Register address
 * @param val   Byte value to write
 * @return I2C_OK on success
 *
 * @example
 * @code
 * // Enable OLED display (SSD1306): set display ON command
 * i2c_reg_write8(bus, 0x3C, 0x00, 0xAF);
 * @endcode
 */
i2c_err_t i2c_reg_write8(i2c_bus_t bus, uint8_t addr, uint8_t reg, uint8_t val);

/**
 * @brief Read a single byte from a device register
 *
 * @param bus       Bus handle
 * @param addr      Device address
 * @param reg       Register address
 * @param[out] val  Pointer to store the read byte
 * @return I2C_OK on success
 *
 * @example
 * @code
 * // Read WHO_AM_I register of MPU-6050 (should return 0x68)
 * uint8_t id;
 * i2c_reg_read8(bus, 0x68, 0x75, &id);
 * @endcode
 */
i2c_err_t i2c_reg_read8(i2c_bus_t bus, uint8_t addr, uint8_t reg, uint8_t *val);

/**
 * @brief Write a 16-bit value to two consecutive registers (big-endian)
 *
 * @param bus   Bus handle
 * @param addr  Device address
 * @param reg   First register address (MSB written here)
 * @param val   16-bit value
 * @return I2C_OK on success
 */
i2c_err_t i2c_reg_write16_be(i2c_bus_t bus, uint8_t addr, uint8_t reg, uint16_t val);

/**
 * @brief Read a 16-bit value from two consecutive registers (big-endian)
 *
 * Used by: ADS1115 (ADC), BME280, BMP280, MPU-6050 raw data
 *
 * @param bus       Bus handle
 * @param addr      Device address
 * @param reg       First register (MSB at reg, LSB at reg+1)
 * @param[out] val  Pointer to store 16-bit result
 * @return I2C_OK on success
 *
 * @example
 * @code
 * // Read raw ALS value from VEML7700 (16-bit big-endian)
 * uint16_t lux_raw;
 * i2c_reg_read16_be(bus, 0x10, 0x04, &lux_raw);
 * @endcode
 */
i2c_err_t i2c_reg_read16_be(i2c_bus_t bus, uint8_t addr, uint8_t reg, uint16_t *val);

/**
 * @brief Read a 16-bit value from two consecutive registers (little-endian)
 *
 * Used by: most STMicroelectronics sensors, Nordic devices
 *
 * @param bus       Bus handle
 * @param addr      Device address
 * @param reg       First register (LSB at reg, MSB at reg+1)
 * @param[out] val  Pointer to store 16-bit result
 * @return I2C_OK on success
 */
i2c_err_t i2c_reg_read16_le(i2c_bus_t bus, uint8_t addr, uint8_t reg, uint16_t *val);

/* ============================================================================
 * BIT MANIPULATION — Modify individual register bits safely
 * ========================================================================== */

/**
 * @brief Set specific bits in a register (read-modify-write)
 *
 * Reads the register, ORs in the mask, writes back.
 * Useful for enabling features without affecting other bits.
 *
 * @param bus   Bus handle
 * @param addr  Device address
 * @param reg   Register address
 * @param mask  Bit mask — 1 = set this bit
 * @return I2C_OK on success
 *
 * @example
 * @code
 * // Enable INT pin on MPU-6050 (bit 0 of INT_ENABLE register 0x38)
 * i2c_reg_set_bits(bus, 0x68, 0x38, 0x01);
 * @endcode
 */
i2c_err_t i2c_reg_set_bits(i2c_bus_t bus, uint8_t addr, uint8_t reg, uint8_t mask);

/**
 * @brief Clear specific bits in a register (read-modify-write)
 *
 * Reads the register, ANDs out the mask, writes back.
 *
 * @param bus   Bus handle
 * @param addr  Device address
 * @param reg   Register address
 * @param mask  Bit mask — 1 = clear this bit
 * @return I2C_OK on success
 *
 * @example
 * @code
 * // Put MPU-6050 to sleep: set SLEEP bit (bit 6) in PWR_MGMT_1 (0x6B)
 * i2c_reg_clear_bits(bus, 0x68, 0x6B, 0x40);
 * @endcode
 */
i2c_err_t i2c_reg_clear_bits(i2c_bus_t bus, uint8_t addr, uint8_t reg, uint8_t mask);

/**
 * @brief Update a bit field within a register
 *
 * Reads the register, masks out the field, ORs in the new value, writes back.
 *
 * @param bus    Bus handle
 * @param addr   Device address
 * @param reg    Register address
 * @param mask   Field mask (e.g., 0x0C for bits [3:2])
 * @param value  New field value (pre-shifted to correct bit position)
 * @return I2C_OK on success
 *
 * @example
 * @code
 * // Set MPU-6050 accelerometer range to ±4g (bits [4:3] of ACCEL_CONFIG = 0x1C)
 * // ±4g = 0b01, bits [4:3] → mask=0x18, value=(1<<3)
 * i2c_reg_update_bits(bus, 0x68, 0x1C, 0x18, 0x08);
 * @endcode
 */
i2c_err_t i2c_reg_update_bits(i2c_bus_t bus, uint8_t addr, uint8_t reg,
                                uint8_t mask, uint8_t value);

/* ============================================================================
 * BUS DIAGNOSTIC FUNCTIONS
 * ========================================================================== */

/**
 * @brief Scan the I2C bus for responding devices
 *
 * Sends address frame to each valid address (0x08–0x77) and records
 * which ones respond with ACK. Essential for debugging wiring issues.
 *
 * @param bus          Bus handle
 * @param found_addrs  Array to receive found addresses (must hold 112 entries)
 * @param[out] count   Number of devices found
 * @return I2C_OK always (no devices found is not an error at this level)
 *
 * @example
 * @code
 * uint8_t addrs[112];
 * uint8_t count;
 * i2c_scan(bus, addrs, &count);
 * printf("Found %u devices:\n", count);
 * for (int i = 0; i < count; i++) {
 *     printf("  0x%02X\n", addrs[i]);
 * }
 * @endcode
 */
i2c_err_t i2c_scan(i2c_bus_t bus, uint8_t *found_addrs, uint8_t *count);

/**
 * @brief Check if a specific device is present on the bus
 *
 * Sends address byte and checks for ACK. Does not transmit any data.
 *
 * @param bus   Bus handle
 * @param addr  7-bit device address to probe
 * @return true if device responded with ACK, false otherwise
 *
 * @example
 * @code
 * if (!i2c_device_present(bus, 0x68)) {
 *     printf("MPU-6050 not found! Check wiring.\n");
 * }
 * @endcode
 */
bool i2c_device_present(i2c_bus_t bus, uint8_t addr);

/**
 * @brief Attempt to recover from a locked-up I2C bus
 *
 * Implements the I2C bus recovery sequence from spec §3.1.16:
 *  1. Send 9 SCL clock pulses (forces slave to release SDA)
 *  2. Generate STOP condition
 *  3. Re-initialize the bus
 *
 * Call this when i2c_get_state() returns I2C_STATE_ERROR or
 * when SDA is stuck LOW (slave mid-transmission on power-cycle).
 *
 * @param bus  Bus handle
 * @return I2C_OK if recovery succeeded and bus is now IDLE
 *
 * @example
 * @code
 * if (i2c_get_state(bus) == I2C_STATE_ERROR) {
 *     if (i2c_recover(bus) != I2C_OK) {
 *         printf("Bus unrecoverable — power cycle required\n");
 *     }
 * }
 * @endcode
 */
i2c_err_t i2c_recover(i2c_bus_t bus);

/**
 * @brief Get the current bus state
 *
 * @param bus  Bus handle
 * @return Current i2c_state_t
 */
i2c_state_t i2c_get_state(i2c_bus_t bus);

/**
 * @brief Retrieve accumulated bus statistics
 *
 * @param bus         Bus handle
 * @param[out] stats  Pointer to stats structure to fill
 * @return I2C_OK on success
 */
i2c_err_t i2c_get_stats(i2c_bus_t bus, i2c_stats_t *stats);

/**
 * @brief Reset bus statistics counters to zero
 *
 * @param bus  Bus handle
 * @return I2C_OK on success
 */
i2c_err_t i2c_reset_stats(i2c_bus_t bus);

/* ============================================================================
 * UTILITY FUNCTIONS
 * ========================================================================== */

/**
 * @brief Convert an error code to a human-readable string
 *
 * @param err  Error code from any API function
 * @return Pointer to static null-terminated error description string
 *
 * @example
 * @code
 * i2c_err_t err = i2c_write(bus, 0x68, data, 2);
 * if (err != I2C_OK) {
 *     printf("I2C error: %s\n", i2c_err_to_string(err));
 * }
 * @endcode
 */
const char *i2c_err_to_string(i2c_err_t err);

/**
 * @brief Validate that an address is in the legal 7-bit range
 *
 * Checks against reserved addresses (0x00–0x07, 0x78–0x7F).
 *
 * @param addr  7-bit address to validate
 * @return true if address is valid and usable
 */
bool i2c_addr_is_valid(uint8_t addr);

/**
 * @brief Get library version as a null-terminated string
 *
 * @return Version string e.g. "2.0.0"
 */
const char *i2c_version(void);

#ifdef __cplusplus
}
#endif

#endif /* I2C_H */
